[[duneistl_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23e5084c5d4c43bd0cd7df408d9f4d99fe5560e0"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "d85258513505274bcd87b2c5c0799d65e1b0827c8dbccf571691f9e2c8a0ebae"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15aae4ec513742ca2ef6f3741b96080745a349b6"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "b828cc20791fe49463f938afd3a07e4ac9cbf0763191a8fa8b30dcf212af1358"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a640a9e15413d835d588b228ae3bb51cda8cdbde"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "8027a8860e3cf0a240028452193e46d7f515607d8169f7bc3fc0a93c22f69093"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.i686-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8114565eee65392044db007f5353d47b7d4c2efa"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "19aaa4b27436748f463ab83c483b548231b97913f64854a8176c662d6e98a0dc"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25b61085dbd518806aa570ace341cde9459ae444"
os = "macos"

    [[duneistl_julia.download]]
    sha256 = "999be41b80ab3e64b906d7d60d0707ceb84c4dfa6adaa881375646c2a1668898"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e674d36f1d089673045502f37566b81528ba2bd"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "a3fb2f34b2a9c48b76e69949b60260ec7d54140c6968baa1c15acb3d4fe7f0e2"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1f0200cb8e225c9b878d61a3b4340ee9716c7c3"
os = "freebsd"

    [[duneistl_julia.download]]
    sha256 = "2a8549091fca83de1862238463c3eafbe57c9e66ef7a89f1ea42d574d1da7529"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99a9962b5bc749be2cb66efd8656841e7925fd3b"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "dfbb383eef48125a01684dcd7d6cd53ea7073782136a1ae6b666385f4f22be26"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.3.1+0/duneistl_julia.v0.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
