[[duneistl_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f05696b11fe69ee551096ddb28989ec79c0fc8b"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "caa45e9757d7529e0a099a6c08bd1a8f0928d4ed429cddf8abdbcecea6025b95"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03b446822c218145d74a799288429d86b4ccd938"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "e7058eab53da082e2036f592997b69f91fbfe85b86312d9e9c235a86bfbf80a8"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efba9363cc5354d5d03f2f29a77dfa64b5d4fe2d"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "dc53a928cd27c7356ec9bd0766edf914cda8e0fe53ef941503474dc1ba5a952f"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.i686-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6211c8d80bd1cac5305ed64bbec048e9fc724f0"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "4d78b6b77b6650c133d6778270acd929d2fd6d69ee776bd802dbd11f3f6d5f14"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.i686-w64-mingw32-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3750d35f3c3a2d0adac7fda69c5d277c93da539e"
os = "macos"

    [[duneistl_julia.download]]
    sha256 = "5cc624b53c66a0af27ccf5e021f758ab7bccdfcbc07ed0bf6d0125c06af9c886"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "532ff1ba86fd6dbd2e7dd27185e6949f4e2ad61f"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "8a87e5989539ce5058d3727bb2e5c47f49fc10a684c5bf9f3336cecc24392ccc"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "811d3dc8a129f450d1fa9f3793d1da81fac8809e"
os = "freebsd"

    [[duneistl_julia.download]]
    sha256 = "dc532ae4ba4c08488fafffab8116a7730b1d2ab7c853c13cf663f1b9484ab067"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83b799a6051cdd085813a0b44681772954db0eeb"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "151db2694933be306c28dbd3f513d87ed8f5796d90ebdc7302dbd88290d93fda"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.1+0/duneistl_julia.v0.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
