[[duneistl_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c0b5a4cc637598ec545a319239aed5c1c6e3c87"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "9d2484dd8280082214e9992d840e1d91ee79cbdcf1d41babc75b45913a40b452"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a82a7e9175ff5adb5d4e017eccb7dd8aebbbdf9"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "d7f5f04de39e3c149005fc7ce8888d26cd0b3dd2cc9ce863c89448eaa7daa6f9"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "602fa931bcbccc8d9a10e551145b5e5087fdc0e2"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "649988ea53985e72b60f1d48a5f9bfacec89e92643919afe9d17d75e2c9b0ab1"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.i686-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb8238fde7c5ea0b5702beff377e47f0e4dee906"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "01c53d3d02e7bdeabe95842a3ea94dbc7c829a700e2d914c9fd0e81dd2a5efcc"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "772be7c9a317b5ec5d7369d0b3412a569675ea7c"
os = "macos"

    [[duneistl_julia.download]]
    sha256 = "e70d3e7977210abf6db81d66d8678232336af32fc22edec354963bb77e2627e6"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a9423d519943f5a9324f141847c1f65fe6be2ca"
libc = "glibc"
os = "linux"

    [[duneistl_julia.download]]
    sha256 = "ee0f1ff5660972b0c2b2f8e5ca79da5f99b40d880d4999c436fd8e169a9c8013"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "948f0270fb30d71de9927ec361ee76afcfd3cde1"
os = "freebsd"

    [[duneistl_julia.download]]
    sha256 = "037fc810ff924159cde21f7005e9aa0930bd81e2ba35d3695bd4be883b67f375"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[duneistl_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eb942328ab692b25b15e2de0a209ed77aa79b93"
os = "windows"

    [[duneistl_julia.download]]
    sha256 = "bbda6171d1e4285a9249ba962a4816e3ebd206eeee6e093aa16307732bd81bc5"
    url = "https://github.com/DeanLym/libduneistlsolver_jll.jl/releases/download/duneistl_julia-v0.2.0+0/duneistl_julia.v0.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
